let
  Origen = Lakehouse.Contents(null),
  Navegación = Origen{[workspaceId = "e859e9b3-5e74-462e-a46d-f701c907f9f1"]}[Data],
  #"Navegación 1" = Navegación{[lakehouseId = "85821590-081b-4a45-9a28-5b870e0264a8"]}[Data],
  #"Navegación 2" = #"Navegación 1"{[Id = "Files", ItemKind = "Folder"]}[Data],
  #"Navegación 3" = #"Navegación 2"{[Name = "Bronze"]}[Content],
  #"Navegación 4" = #"Navegación 3"{[Name = "tiempo.xlsx"]}[Content],
  #"Libro de Excel importado" = Excel.Workbook(#"Navegación 4", null, true),
  #"Navegación 5" = #"Libro de Excel importado"{[Item = "Tabla1", Kind = "Table"]}[Data],
  #"Tipo de columna cambiado" = Table.TransformColumnTypes(#"Navegación 5", {{"Fecha", type date}}, "es"),
  #"Columna duplicada" = Table.DuplicateColumn(#"Tipo de columna cambiado", "Fecha", "Fecha - Copia"),
  #"Año extraído" = Table.TransformColumns(#"Columna duplicada", {{"Fecha - Copia", each Date.Year(_), type nullable number}}),
  #"Columnas con nombre cambiado" = Table.RenameColumns(#"Año extraído", {{"Fecha - Copia", "Anio"}}),
  #"Columna duplicada 1" = Table.DuplicateColumn(#"Columnas con nombre cambiado", "Fecha", "Fecha - Copia"),
  #"Mes extraído" = Table.TransformColumns(#"Columna duplicada 1", {{"Fecha - Copia", each Date.Month(_), type nullable number}}),
  #"Columnas con nombre cambiado 1" = Table.RenameColumns(#"Mes extraído", {{"Fecha - Copia", "nuMes"}}),
  #"Columna duplicada 2" = Table.DuplicateColumn(#"Columnas con nombre cambiado 1", "Fecha", "Fecha - Copia"),
  #"Nombre del mes extraído" = Table.TransformColumns(#"Columna duplicada 2", {{"Fecha - Copia", each Date.MonthName(_), type nullable text}}),
  #"Columnas con nombre cambiado 2" = Table.RenameColumns(#"Nombre del mes extraído", {{"Fecha - Copia", "nombre_mes"}}),
  #"Columna duplicada 3" = Table.DuplicateColumn(#"Columnas con nombre cambiado 2", "Fecha", "Fecha - Copia"),
  #"Semana del año" = Table.TransformColumns(#"Columna duplicada 3", {{"Fecha - Copia", each Date.WeekOfYear(_), type nullable number}}),
  #"Columnas con nombre cambiado 3" = Table.RenameColumns(#"Semana del año", {{"Fecha - Copia", "semana_anio"}}),
  #"Columna duplicada 4" = Table.DuplicateColumn(#"Columnas con nombre cambiado 3", "Fecha", "Fecha - Copia"),
  #"Semana del mes calculada" = Table.TransformColumns(#"Columna duplicada 4", {{"Fecha - Copia", each Date.WeekOfMonth(_), type nullable number}}),
  #"Columnas con nombre cambiado 4" = Table.RenameColumns(#"Semana del mes calculada", {{"Fecha - Copia", "Semana_mes"}}),
  #"Columna duplicada 5" = Table.DuplicateColumn(#"Columnas con nombre cambiado 4", "Fecha", "Fecha - Copia"),
  #"Día extraído" = Table.TransformColumns(#"Columna duplicada 5", {{"Fecha - Copia", each Date.Day(_), type nullable number}}),
  #"Columnas con nombre cambiado 5" = Table.RenameColumns(#"Día extraído", {{"Fecha - Copia", "nuDia"}}),
  #"Columna duplicada 6" = Table.DuplicateColumn(#"Columnas con nombre cambiado 5", "Fecha", "Fecha - Copia"),
  #"Nombre del día extraído" = Table.TransformColumns(#"Columna duplicada 6", {{"Fecha - Copia", each Date.DayOfWeekName(_), type nullable text}}),
  #"Columnas con nombre cambiado 6" = Table.RenameColumns(#"Nombre del día extraído", {{"Fecha - Copia", "nombre_dia"}}),
  #"Personalizado agregado" = Table.AddColumn(#"Columnas con nombre cambiado 6", "FechaID",  each Number.FromText(Date.ToText([Fecha], "yyyyMMdd")),
    Int64.Type),
  #"Columnas reordenadas" = Table.ReorderColumns(#"Personalizado agregado", {"FechaID", "Fecha", "Anio", "nuMes", "nombre_mes", "semana_anio", "Semana_mes", "nuDia", "nombre_dia"})
in
  #"Columnas reordenadas"